services:
  app:
    build:
      context: backend
      dockerfile: Dockerfile

    container_name: to-do
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - app-network

    volumes:
      - ./backend:/app

  db:
    image: postgres
    container_name: to_do_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo
      POSTGRES_PORT: 5435
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: